# Generated by Django 4.2.13 on 2024-09-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_shop_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='price',
            field=models.IntegerField(),
        ),
    ]
